apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::445567085619:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-x9t2ZQTFsrGI
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: | 
    - groups: 
      - roboshop-trainee 
      userarn: arn:aws:iam::445567085619:user/suresh
      username: suresh 
kind: ConfigMap
metadata:
  creationTimestamp: "2026-07-14T09:08:05Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1186"
  # uid: 34618cec-548e-4210-a3ce-22dc522d6c82
